POST http://localhost:3000/api/generate-token?role=mahasiswa

###

POST https://website-pinjam-lab.netlify.app/api/submit-loan

{
    "nama" : "Fahrezi Rizqiawan",
    "nomor_hp": "089662690020",
    "npm_nidn": "201552020008",
    "tanggal" : "27 Agustus 2025",
    "jam": "17.19",
    "keperluan": "Praktek komputer",
}

###

GET http://website-pinjam-lab-production.up.railway.app/api/validate-token?token=9c128551-fb4a-4481-b9a6-5ad6697e2834